- name: ubuntu | ensure google apt signing key is present
  apt_key: url=https://dl-ssl.google.com/linux/linux_signing_key.pub state=present

- name: ubuntu | ensure google chrome repository is present
  apt_repository:
    repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ {{ channel }} main"
    filename: "google-chrome"
    state: present
    update_cache: yes

- name: ubuntu | ensure google chrome is present
  apt:
    name: google-chrome-{{ channel }}
    state: latest
