FROM ubuntu:disco

RUN apt-get update && apt-get -y install \
    make \
    sudo \
    virtualenv

RUN useradd dev \
    && echo "dev ALL=(root) NOPASSWD:ALL" > /etc/sudoers.d/dev \
    && chmod 0440 /etc/sudoers.d/dev \
    && ln -sf /usr/bin/python3 /usr/bin/python

USER dev
