- name: fedora | ensure google chrome repository is installed
  template:
    src: google-chrome.repo.j2
    dest: /etc/yum.repos.d/google-chrome.repo
    owner: root
    group: root
    mode: 0644

- name: fedora | ensure google chrome is installed
  dnf:
    name: google-chrome-{{ channel }}
    state: latest
