bazel_version: "0.23.0"
bazel_checksum: "sha256:7ea1baf4506af2f8a596052c675b43a8a8a36b737347b4f3d3466f0e202ea2a9"
bazel_installer_url: https://github.com/bazelbuild/bazel/releases/download/{{ bazel_version }}/bazel-{{ bazel_version }}-installer-linux-x86_64.sh